name: velocimetro
description: "Velocímetro + Hodômetro com HUD"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0-196.0.dev

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  provider: ^6.1.5+1
  syncfusion_flutter_gauges: ^31.1.19
  wakelock_plus: ^1.2.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true # Generate icons for Android
  image_path: "assets/icon/icone.png" # Path to your icon image