name: velocimetro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0-196.0.dev

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  provider: ^6.1.5+1
  syncfusion_flutter_gauges: ^31.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
